site_url: https://staging.geosmash.net

backend:
  name: git-gateway
  branch: staging
media_folder: SMASH/static/img
public_folder: SMASH/img

collections:
  - name: 'core'
    label: 'SMASH Core Info'
    files:
      - label: 'SMASH Contact Info'
        name: 'contact'
        file: 'SMASH/content/contact.yaml'
        fields:
          - label: "Social Networks"
            name: 'socialNetworks'
            widget: 'list'
            summary: "{{fields.name}}"
            allow_add: true
            fields:
              - {label: 'Network Name', name: 'name', widget: 'string'}
              - {label: 'Network Icon', name: 'icon', widget: 'string'}
              - {label: 'Network Link', name: 'link', widget: 'string'}
      - label: 'SMASH Footer'
        name: 'footer'
        file: 'SMASH/content/footer.yaml'
        fields:
          - label: 'Left Text'
            name: 'footerText'
            widget: 'markdown'
      - label : "SMASH Header"
        name: 'header'
        file: 'SMASH/content/header.yaml'
        fields:
          - label: 'Navigation Menu Items'
            name: 'navMenuItems'
            widget: 'list'
            fields:
              - {label: 'Root Navigation Item Name', name: 'title', widget: 'string'}
              - name: 'rowItems'
                label: 'Row Items'
                summary: "{{fields.title}}"
                widget: 'list'
                fields:
                  - {label: 'Row Item Name', name: 'title', widget: 'string'}
                  - {label: 'Row Item Link', name: 'link', widget: 'string'}
                  - {label: 'Row Item Icon', name: 'icon', widget: 'string'}
              - label: "Bottom Items"
                name: 'bottomItems'
                widget: "list"
                fields:
                  - {label: 'Bottom Item Name', name: 'title', widget: 'string'}
                  - {label: 'Bottom Item Link', name: 'link', widget: 'string'}
                  - {label: 'Bottom Item Icon', name: 'icon', widget: 'string'}
          - label: "End Button"
            name: "button"
            widget: "object"
            fields:
              - {label: 'Button Title', name: 'title', widget: 'string'}
              - {label: 'Button Link', name: 'link', widget: 'string'}
      - label : "Index Page"
        name: 'index'
        file: 'SMASH/content/index.yaml'
        fields:
          - {label: 'Index title', name: 'title', widget: 'string'}
          - {label: 'Index Subtitle', name: 'subtitle', widget: 'string'}
          - {label: 'Index Short Sentence', name: 'shortSentence', widget: 'text'}
      - label : "Objective Page"
        name: 'objective'
        file: 'SMASH/content/objective.yaml'
        fields:
          - {label: 'Objective', name: 'objective', widget: 'markdown'}    
  - name: 'news'
    label: 'News'
    folder: 'SMASH/content/news'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
      - {label: 'Title', name: 'title', widget: 'string' }
      - {label: 'Author', name: 'author', widget: 'string', }
      - {label: 'Date', name: 'date', widget: 'datetime'}
      - {label: 'News content', name: 'body', widget: 'markdown'}
  - name: 'people'
    label: 'People'
    folder: 'SMASH/content/people'
    format: 'yaml'
    create: true
    slug: {{fields.name}}
    fields:
      - {label: 'Name', name: 'name', widget: 'string'}
      - {label: 'Role', name: 'role', widget: 'string'}
      - label: 'Bio'
        name: 'bio'
        widget: 'markdown'
        editor_components:
          - 'bold'
          - 'italic'
          - 'link'
          - 'quote'
          - 'bulleted-list'
          - 'numbered-list'
      - label: "Social Links"
        name: 'socialLinks'
        widget: 'list'
        summary: "{{fields.name}}"
        allow_add: true
        fields:
          - {label: 'Network Name', name: 'name', widget: 'string'}
          - {label: 'Network Icon', name: 'icon', widget: 'string'}
          - {label: 'Network Link', name: 'link', widget: 'string'}
  - name: 'smaart'
    label: 'SMART'
    folder: 'SMASH/content/smaart'
    format: 'yaml'
    create: true
    slug: '{{presenter}}-{{date}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'string' }
      - {label: 'Presenter', name: 'presenter', widget: 'string' }
      - {label: 'Date', name: 'date', widget: 'datetime'}
      - {label: 'YouTube Video ID', name: 'videoId', widget: 'string'}
